# Generated by Django 5.1.4 on 2026-06-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="active_theme",
            field=models.SlugField(default="default", verbose_name="active theme"),
        ),
    ]
