# Generated by Django 5.1.4 on 2026-06-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0002_organization_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="seosettings",
            name="allow_ai_crawlers",
            field=models.BooleanField(
                default=True,
                help_text="Let GPTBot, ClaudeBot, PerplexityBot, Google-Extended, etc. crawl the site (robots.txt). Turn off to ask them not to.",
                verbose_name="allow AI answer-engine crawlers",
            ),
        ),
    ]
