# Generated by Django 5.1.4 on 2026-06-17 13:25

import apps.media.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=apps.media.models.upload_to, verbose_name="file"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="library/thumbnails/",
                        verbose_name="thumbnail",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="title")),
                ("alt_text", models.CharField(blank=True, max_length=255, verbose_name="alt text")),
                (
                    "mime_type",
                    models.CharField(blank=True, max_length=100, verbose_name="MIME type"),
                ),
                ("file_size", models.PositiveBigIntegerField(default=0, verbose_name="file size")),
                ("width", models.PositiveIntegerField(blank=True, null=True, verbose_name="width")),
                (
                    "height",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="height"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_assets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "media asset",
                "verbose_name_plural": "media assets",
                "ordering": ["-created_at"],
            },
        ),
    ]
